const ACCESS_TOKEN_TITLE = process.env.NEXT_PUBLIC_ACCESS_TOKEN;
const REFRESH_TOKEN_TITLE = process.env.NEXT_PUBLIC_REFRESH_TOKEN;
const IS_USER = process.env.NEXT_PUBLIC_IS_USER;

export { ACCESS_TOKEN_TITLE, REFRESH_TOKEN_TITLE, IS_USER };
