import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import ErrorBoundary from '@/components/common/ErrorBoundary';
import ThemeProvider from '@/components/common/ThemeProvider';
import Providers from '@/components/common/Provider';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ErrorBoundary>
          <Providers>
            <ThemeProvider>{children}</ThemeProvider>
          </Providers>
        </ErrorBoundary>
      </body>
    </html>
  );
}
